version: "2"

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kpurdon/requirecodeowners

linters:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
