name: "Require CODEOWNERS"
description: "Validate that specified directories have CODEOWNERS entries"
author: "kpurdon"

branding:
  icon: "shield"
  color: "blue"

inputs:
  config:
    description: "Path to config file (default: .requirecodeowners.yml)"
    required: false
    default: ""
  codeowners-path:
    description: "Path to CODEOWNERS file (auto-detected if not specified)"
    required: false
    default: ""
  version:
    description: "Version of requirecodeowners to use"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Run requirecodeowners
      shell: bash
      env:
        INPUT_CONFIG: ${{ inputs.config }}
        INPUT_CODEOWNERS_PATH: ${{ inputs.codeowners-path }}
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Setup"
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        [[ "$ARCH" == "x86_64" ]] && ARCH="amd64"
        [[ "$ARCH" == "aarch64" ]] && ARCH="arm64"

        if [[ "$INPUT_VERSION" == "latest" ]]; then
          URL="https://github.com/kpurdon/requirecodeowners/releases/latest/download/requirecodeowners_${OS}_${ARCH}"
        else
          URL="https://github.com/kpurdon/requirecodeowners/releases/download/${INPUT_VERSION}/requirecodeowners_${OS}_${ARCH}"
        fi

        curl -sSL "$URL" -o /tmp/requirecodeowners
        chmod +x /tmp/requirecodeowners
        echo "::endgroup::"

        ARGS=""
        [[ -n "$INPUT_CONFIG" ]] && ARGS="--config=$INPUT_CONFIG"
        [[ -n "$INPUT_CODEOWNERS_PATH" ]] && ARGS="$ARGS --codeowners-path=$INPUT_CODEOWNERS_PATH"

        /tmp/requirecodeowners $ARGS
