name: "Require CODEOWNERS"
description: "Validate that specified directories have CODEOWNERS entries"
author: "kpurdon"

branding:
  icon: "shield"
  color: "blue"

inputs:
  config:
    description: "Path to config file (default: .requirecodeowners.yml)"
    required: false
    default: ""
  codeowners-path:
    description: "Path to CODEOWNERS file (auto-detected if not specified)"
    required: false
    default: ""
  version:
    description: "Version of requirecodeowners to use (defaults to action version)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Determine version
      id: version
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          echo "version=${{ inputs.version }}" >> "$GITHUB_OUTPUT"
        else
          echo "version=${{ github.action_ref }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Determine platform
      id: platform
      shell: bash
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then
          ARCH="amd64"
        elif [ "$ARCH" = "aarch64" ]; then
          ARCH="arm64"
        fi
        echo "os=$OS" >> "$GITHUB_OUTPUT"
        echo "arch=$ARCH" >> "$GITHUB_OUTPUT"

    - name: Download requirecodeowners
      shell: bash
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        OS="${{ steps.platform.outputs.os }}"
        ARCH="${{ steps.platform.outputs.arch }}"
        URL="https://github.com/kpurdon/requirecodeowners/releases/download/${VERSION}/requirecodeowners_${OS}_${ARCH}"
        echo "Downloading $URL"
        curl -sL "$URL" -o /tmp/requirecodeowners
        chmod +x /tmp/requirecodeowners

    - name: Run validation
      shell: bash
      run: |
        ARGS=""
        if [ -n "${{ inputs.config }}" ]; then
          ARGS="--config=${{ inputs.config }}"
        fi
        if [ -n "${{ inputs.codeowners-path }}" ]; then
          ARGS="$ARGS --codeowners-path=${{ inputs.codeowners-path }}"
        fi
        /tmp/requirecodeowners $ARGS
