name: "Require CODEOWNERS"
description: "Validate that specified directories have CODEOWNERS entries"
author: "kpurdon"

branding:
  icon: "shield"
  color: "blue"

inputs:
  config:
    description: "Path to config file (default: .requirecodeowners.yml)"
    required: false
    default: ""
  codeowners-path:
    description: "Path to CODEOWNERS file (auto-detected if not specified)"
    required: false
    default: ""
  version:
    description: "Version of requirecodeowners to use"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Setup
      id: setup
      shell: bash
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        [[ "$ARCH" == "x86_64" ]] && ARCH="amd64"
        [[ "$ARCH" == "aarch64" ]] && ARCH="arm64"
        VERSION="${{ inputs.version }}"
        if [[ "$VERSION" == "latest" ]]; then
          URL="https://github.com/kpurdon/requirecodeowners/releases/latest/download/requirecodeowners_${OS}_${ARCH}"
        else
          URL="https://github.com/kpurdon/requirecodeowners/releases/download/${VERSION}/requirecodeowners_${OS}_${ARCH}"
        fi
        curl -sSL "$URL" -o /tmp/requirecodeowners
        chmod +x /tmp/requirecodeowners
        ARGS=""
        [[ -n "${{ inputs.config }}" ]] && ARGS="--config=${{ inputs.config }}"
        [[ -n "${{ inputs.codeowners-path }}" ]] && ARGS="$ARGS --codeowners-path=${{ inputs.codeowners-path }}"
        echo "args=$ARGS" >> "$GITHUB_OUTPUT"

    - name: Require CODEOWNERS
      shell: bash
      run: /tmp/requirecodeowners ${{ steps.setup.outputs.args }} >> "$GITHUB_STEP_SUMMARY"
